# system
alias c="clear"
alias proxy="http_proxy=http://127.0.0.1:1086 https_proxy=http://127.0.0.1:1086"
alias lg="lazygit"
alias f="ranger"
alias s="screenfetch"
alias vim="nvim"
alias vi="nvim"
alias svim="sudo -E nvim"
alias svi="sudo -E nvim"
alias downgrade="proxy DOWNGRADE_FROM_ALA=1 downgrade"
alias cat="bat"
alias ls="lsd"
alias find="fd"
alias grep="rg"
alias cmd="proxy tldr"
alias rec="asciinema rec"
alias p="ps aux | grep"
alias yay="proxy yay"
alias t="tmux"
alias s="neofetch | lolcat"
alias port="netstat -anp | grep"
alias storage="du -h --max-depth=1"
alias top="htop"
alias git="proxy git"
alias free="duf"
alias k="kubectl"
alias clean_pkg="sudo pacman -R \$(pacman -Qdtq) && yay -R \$(pacman -Qdtq)"
alias air="air -c .air.toml"

# time
alias set_time="sudo timedatectl set-time"
alias sync_time="sudo ntpdate time.nist.gov"

