# system
alias c="clear"
alias proxy="http_proxy=http://127.0.0.1:1086 https_proxy=http://127.0.0.1:1086"
alias lg="lazygit"
alias f="ranger"
alias s="screenfetch"
alias vim="nvim"
alias vi="nvim"
alias svim="sudo -E nvim"
alias svi="sudo -E nvim"
alias downgrade="proxy DOWNGRADE_FROM_ALA=1 downgrade"
alias cat="bat"
alias ls="colorls"
alias find="fd"
alias grep="rg"
alias cmd="tldr"
alias rec="asciinema rec"
alias p="ps aux | grep"
alias yay="proxy yay"
alias t="tmux"
alias s="neofetch"
alias port="netstat -anp | grep"
alias storage="du -h --max-depth=1"
alias top="htop"
